Display stock chart after click on company name in Search Page
Iromix/uek-stock-traders pull request #15
Opened 2018-04-26 20:07 UTC by PioKon993

2018-04-27 07:04 UTC, Ares1112 requested changes
Jak w search stocks klikam plusa żeby dodać akcje do portfela to przechodzi na stronę szczegółów akcji, dodatkowo jedna mała poprawka.

2018-04-27 07:04 UTC, Ares1112 commented on src/pages/stock_search/stock_search.page.ts
> +    private stock_chart_page(symbol: string, companyName: string) {
Może zmienić nazwę metody na openStockChartPage?

2018-04-29 11:00 UTC, Ares1112 reviewed
Wyświetliłbym jakiś Toast po dodaniu akcji do portfela żeby user wiedział, że jest ok

2018-04-29 11:58 UTC, PioKon993 commented
Dodałem ten toast po dodaniu akcji do portfela

2018-04-29 12:14 UTC, Ares1112 approved these changes

2018-04-29 12:19 UTC, merged